name: super_translator
description: A simple Flutter app using Google Translator API
author: Viktor Sinelnikov

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_dotenv: ^4.0.0-nullsafety.0
  http: ^0.13.1
  moor: ^4.2.0
  sqlite3_flutter_libs: ^0.4.1
  path_provider: ^2.0.1
  path: ^1.8.0
  freezed_annotation: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^4.2.0
  build_runner: ^1.12.2
  freezed: ^0.14.1+1

flutter:
  uses-material-design: true
  assets:
    - .env
